#!/bin/bash

case "$1" in
  list )		case "$2" in
		  "" | added )	echo ""
					echo "List of the added repositories:"
					echo ""
					echo -n $(color ltgreen)" * main			     [Rsync	] (`cat /etc/portage/repository.d/current | sed 's/\"//g'`		)"$(color off)
					layman -l
					exit 0
					;;
		  all )		echo ""
				echo $(color ltyellow)"List of the available repositories:"$(color off)
				layman -Lq
				exit 0
				;;
		  main )	echo ""
				echo "List of the available main repositories:"
				echo ""
				
		esac
		;;
  add )	if echo "$2" | grep 'rsync' &>/dev/null 
		then
		  if [ -z "$3" ]
		  then
		    echo "Please, specify a depository address!!"
		    exit 1
		  elif [ -z "$4" ]
		  then
		    echo "Please, specify your repository name!!"
		    exit 1
		  else
		    echo "$3" > /etc/portage/depository.d/"$4"
		    sed -i 's/\(.*\)/"\1"/' /etc/portage/depository.d/"$4"
		    echo "$2" > /etc/portage/repository.d/"$4"
		    sed -i 's/\(.*\)/"\1"/' /etc/portage/repository.d/"$4"
		    echo "Repository "$4" was added"
		    exit 0
		  fi
		else
		  if [ -z "$2" ]
		  then
		    echo $(color ltred)"Please, specify repository name"$(color off)
		    exit 1
		  fi
		echo ""
		echo -n $(color ltgreen)"Adding "$2" repository:"$(color off)
		  if layman -a "$2"
		  then
		    touch /etc/portage/keywords.d/"$2"
		    echo "*/*::"$2" ~amd64" > /etc/portage/keywords.d/"$2"
		    echo -en '\033[A'
		    echo $(color ltgreen)""$2" repository successfully added"$(color off)
		    echo ""
		    exit 0
		  else
		    echo -en '\033[A'
		    echo $(color ltred)"Failed to add "$2" repository"$(color off)
		    echo ""
		    exit 1
		  fi
		fi
		;;

esac

exit 0
		  